sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t paragbaxi/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true paragbaxi/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: 'us-east-2'
    app: 'Docker-env'
    env: 'DockerEnv-env'
    bucket_name: 'elasticbeanstalk-us-east-2-127362753546'
    bucket_path: 'Docker-env'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
